# Dependencies
markdown: redcarpet
highlighter: pygments

# Setup
name: Skeleton Jekyll Gulp Starter Kit
title: "Skeleton+"
tagling: ""
description: ""

source: src
destination: web
# Local Development
# baseurl: ""

# Publishing
baseurl: "http://greendius.github.io/skeleton" # the subpath of your site, e.g. /blog/
# url: "http://greendius.github.io/skeleton/" # the base hostname & protocol for your site

version: alpha

permalink: pretty

# Others
author:
  name: "K Worapon"
  url: ""

github:
  repo: ""